import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class PlayersService {


  private teamOnePlayers : any[]= [
    {
      id       : 1,
      name     : 'Rodolfo Soto',
      age      : 28,
      position : 'Pivot',
      jersey_n : 36,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 2,
      name     : 'Wilson Muñoz',
      age      : 25,
      position : 'Pivot',
      jersey_n : 9,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 3,
      name     : 'Nicolás Soto',
      age      : 25,
      position : 'Base',
      jersey_n : 11,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 4,
      name     : 'Patricio Chiguay',
      age      : 26,
      position : 'Base/Escolta',
      jersey_n : 41,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 5,
      name     : 'Sebastián Rivera',
      age      : 23,
      position : 'Pivot',
      jersey_n : 10,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 6,
      name     : 'Fabián Guzman',
      age      : 28,
      position : 'Pivot',
      jersey_n : 37,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 7,
      name     : 'Diego Cornejo',
      age      : 32,
      position : 'Pivot',
      jersey_n : 90,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 8,
      name     : 'Eric Bueno',
      age      : 25,
      position : 'Base',
      jersey_n : 91,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 9,
      name     : 'Sven Sielfeld',
      age      : 26,
      position : 'Base/Escolta',
      jersey_n : 93,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 10,
      name     : 'Joaquín Jerez',
      age      : 23,
      position : 'Pivot',
      jersey_n : 6,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 11,
      name     : 'Pablo Sánchez',
      age      : 26,
      position : 'Base/Escolta',
      jersey_n : 94,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 12,
      name     : 'Joaquín Jerez',
      age      : 23,
      position : 'Pivot',
      jersey_n : 95,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
  ];

  private teamTwoPlayers : any[]= [
    {
      id       : 6,
      name     : 'Tomás Gutierrez',
      age      : 23,
      position : 'Escolta/Alero',
      jersey_n : 25,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 7,
      name     : 'Tomás Cofré',
      age      : 32,
      position : 'Base/Escolta',
      jersey_n : 16,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 8,
      name     : 'Alex Gutierrez',
      age      : 25,
      position : 'Base, Alero',
      jersey_n : 30,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 9,
      name     : 'Sergio Santos',
      age      : 23,
      position : 'Pivot',
      jersey_n : 5,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
    {
      id       : 10,
      name     : 'Benjamin Novoa',
      age      : 19,
      position : 'Pivot',
      jersey_n : 22,
      in_game  : false,
      rebounds : 0,
      points   : 0,
      assists  : 0,
      free_sht : 0,
      fr_sh_at : 0,
      doubles  : 0,
      three    : 0,
      gen_at   : 0,
      doubles_at  : 0,
      three_at    : 0,
      general_percent : "0%",
      fr_sht_percent  : "0%",
      three_percent   : "0%",
      double_percent  : "0%",
      minutes_played  : 0,
      fouls_in_game   : 0,
      fouls           : [ { i : 1, val : 0}, { i : 2, val : 0 }, { i : 3 , val : 0 }, { i : 4 , val : 0}, { i : 5, val : 0 } ]
    },
  ];
  constructor() { }

  public getPlayersByTeamId( id : number ){
    if ( id == 1 ){
      return this.teamOnePlayers;
    }
    else{
      return this.teamTwoPlayers;
    }
  }
}
